export const SEARCH_LIST_ADD = 'SEARCH_LIST_ADD';
export const SEARCH_LIST_EMPTY = 'SEARCH_LIST_EMPTY';
export const SEARCH_LIST_SAVE_PARAMS = 'SEARCH_LIST_SAVE_PARAMS';
export const SEARCH_LIST_SAVE_CITY = 'SEARCH_LIST_SAVE_CITY';

export const FAVORITES_SAVE = 'FAVORITES_SAVE';
export const FAVORITES_DELETE_ITEM = 'FAVORITES_DELETE_ITEM';
export const FAVORITES_LOAD = 'FAVORITES_LOAD';

export const CHANGE_TEMP_UNIT = 'CHANGE_TEMP_UNIT';
export const FORCAST_FC_UPDATE = 'FORCAST_FC_UPDATE';
export const FAVORITES_FC_UPDATE = 'FAVORITES_FC_UPDATE';

export const FORCAST_LIST = 'FORCAST_LIST';

export const SAVE_INIT_CITY_NAME = 'SAVE_INIT_CITY_NAME';
export const CHANGE_ICON = 'CHANGE_ICON';

export const STYLE = 'STYLE';